### ISSUE TITLE
subscript not working.

### ISSUE THREAD

**Issue by imjbmkz** [golopot/tex-to-unicode#23]
Hi. I just started using the add-in to write math equations on my article. I noticed that subscripts aren't working. I tried to write a simple linear regression model as an equation y = β_0 + β_1X_i. The underscores are kept and is updated to LaTex format. How do I fix this? Thanks.

**Comment by imjbmkz** [comment]
It's also the same for superscript. Typing ∑^n does not work either.

**Comment by golopot** [comment]
Can you try enabling the options by clicking the extension in the chrome tool bar?

**Comment by imjbmkz** [comment]
I see the options button but it's greyed out. I can't click it.

**Comment by imjbmkz** [comment]
Got it. I saw the tickbox now. Thanks a lot! Appreciate it.
