### ISSUE TITLE
Add capability to convert underscript and superscript

### ISSUE THREAD

**Issue by golopot** [golopot/tex-to-unicode#3]

**Comment by golopot** [comment]
Completed by 6abbb18d44dc4e7d3a047aaaa2d88d91306f0a92.

**Comment by kbjiang** [comment]
Hi, the underscript/superscript function does not work for me. I was testing in the 'try it here' spaces on https://golopot.github.io/tex-to-unicode/ using Chrome.

**Comment by golopot** [comment]
The underscript/superscript functionality is disabled by default. In the extension ui there is a checkbox to enable it.

For the "try it here" section currently there is no this option.

**Comment by mbyt** [comment]
First of all thanks for this great extension!

I really like it, for the math stuff it would be really cool to have the underline and superscript function working, which currently does not work for me.

My question is, what is the "extension ui"? I am using the firefox plugin version, `about:addons` looks as follows:

![image](https://user-images.githubusercontent.com/1878241/54223345-92ae0600-44f7-11e9-8f8e-9559df35dc74.png)

I mean, in the above clips I cannot find a options menu in which I could configure a checkbox to enable underscript/superscript functionality.

**Comment by golopot** [comment]
The options section locates in the popup which shows up when you click the addon icon.

I do think a standard options page is an important missing feature. Thanks a lot for your feedback!

![321](https://user-images.githubusercontent.com/16285118/54250222-dea38e00-457d-11e9-87a1-29445b28dab5.jpg)

**Comment by mbyt** [comment]
uups, my bad, I did not see that. Yes, I can confirm, with that option it works like a charm.

Thank you so much for this marvelous plugin!
