### ISSUE TITLE
Nested subscripts would be nice

### ISSUE THREAD

**Issue by cfarah-anno** [golopot/tex-to-unicode#35]
Trying to do the equivalent of nested subscripts. In LaTeX, I would do the following: a_{b_{c_{d_e}}} . Is this feature one that others have requested? Thanks!

**Comment by yehoshuapw** [comment]
how exactly do you propose that to work in Unicode? I don't think subsubscript symbols exist.

**Comment by cfarah-anno** [comment]
That would be useful. Wouldn't it? :) 

Closing ticket.

**Comment by yehoshuapw** [comment]
> That would be useful. Wouldn't it? :)

indeed it would ;)

**Comment by yehoshuapw** [comment]
this actually can be done, with converting to images (instead of pure text). this will not be as useful for some things, and will be better for others.
either using "real" latex, or even MathJax can output svg.

but that is out of the scope of this extension. (I think)

**Comment by cfarah-anno** [comment]
So @yehoshuapw , that is exactly what I did for my Medium article. It's not as pretty as having dynamically rendered math, but it worked fine. Thanks though!

**Comment by yehoshuapw** [comment]
that works.
If you have control over the HTML you can use MathML - and some things will be able to create that from LaTeX for you,
or you can use plain MathJaX - which has the added benefit of being much more portable.

good luck!

**Comment by cfarah-anno** [comment]
Makes perfect sense. For the Medium renderer, I don't have control over, but yes, great advice in general. Thanks again. For your reference, I did make use of the tool for all of the simpler mathematical expressions and it worked great.
