### ISSUE TITLE
source of tex/unicode mapping?

### ISSUE THREAD

**Issue by jpreiss** [golopot/tex-to-unicode#6]
Hi, I am making a command line tool implementing tex-to-unicode functionality. I copied the symbol table from your `symbols.js` and I would like to attribute the original source. Did you assemble it yourself or get it from somewhere else? Thanks!

**Comment by golopot** [comment]
I assembled it from multiple sources so it is hard to find a source that resemble this file.

**Comment by jpreiss** [comment]
Ok thanks, I will cite you.
